title: "My Journey to Becoming a Software Engineer"
description: "Documenting my progress as a WGU student learning Python and working toward becoming a software engineer."
theme: minima

include:
  - _includes/header.html

  include:
  - _includes/footer.html
